theme = [
    ('list-header', '', '', '', '', ''),
    ('list-header-column', '', '', '', 'light cyan', ''),
    ('list-header-column-separator', 'black', 'dark gray', '', 'black', ''),
    ('striped-table-row', '', '', '', '', ''),
    ('reveal focus', 'black', 'dark blue', 'standout', 'black', 'dark blue'),
    ('message status', 'white', 'dark blue', 'standout', 'white', 'dark blue'),
    ('message error', 'white', 'dark red', 'standout', 'dark blue', 'dark red'),
    ('status', 'dark magenta', 'black', 'standout', 'dark magenta', 'black'),
    ('flash off', 'black', 'black', 'standout', 'black', 'black'),
    ('flash on', 'white', 'black', 'standout', 'white', 'black'),
    ('pop_up', 'white', 'black', '', 'white', 'black'),
    ('button action', 'white', 'light red', '', 'white', 'light red'),
    ('button cancel', 'black', 'light gray', '', 'black', 'light gray'),
]
